import sys
import os

startBuildScriptTag = '/* --- Start Generated by build Script --- */\n'
endBuildScriptTag = '/* ---- End Generated by build Script --- */\n'

fileName = "Certificate.h"
justClean = False
skip = False
for i in range(len(sys.argv)):
    if skip:
        skip = False
        continue
    if sys.argv[i] in ('-f', "--file"):
        fileName = sys.argv[i+1]
        skip = True
    elif sys.argv[i] in ('-c', '--clean'):
        justClean = True


if justClean:
    cFileName = fileName[0:fileName.rfind(".")].strip()+'.c'
    writeFile = ""
    if os.path.isfile(cFileName):
        filePtr = open(cFileName,"r")
        file = filePtr.read()
        filePtr.close()

        startGenerated = file.find(startBuildScriptTag)
        endGenerated = file.find(endBuildScriptTag) + len(endBuildScriptTag)

        if startGenerated == -1 or endGenerated == -1:
            os.remove(cFileName)
        
        writeFile = file[:startGenerated] + file[endGenerated:]
        filePtr = open(cFileName, "w")
        filePtr.write(writeFile)
        filePtr.close()
        if len(writeFile.strip()) == 0:
            os.remove(cFileName)
    exit()


filePtr = open(fileName, "r")
file = filePtr.read()
filePtr.close()

packTable = {
    "uint8_t" : "*iter = [value];\n",
    "uint24" : "get_uint24_bytes(iter, [value]);\n",
    "unsigned char*" : "memcpy([value], iter, [length]);\n"
}
unpackTable = {
    "uint8_t" : "[value] = *iter;\n",
    "uint24" : "get_uint24_num(&[value], iter);\n",
    "unsigned char*" : "[value] = malloc([length]);\nmemcpy([value], iter, [length]);\n"
}
lengthTable = {
    "uint8_t" : 1,
    "uint24" : 3,
    "unsigned char*" : "[value]_length"
}

mainStart = file.find("--- main ---")
if mainStart == -1:
    exit()

mainAfter = file[mainStart:]

structStart = mainAfter.find("{")+1
structEnd = mainAfter.find("}")

struct = mainAfter[structStart:structEnd]

structNameEnd = mainAfter[structEnd:].find(";")
temp = mainAfter[structEnd:]
structName = temp[1:structNameEnd].strip()
structNameLower = structName.lower()

entrys = struct.split("\n")
newEntrys = []
for i in range(len(entrys)):
    entrys[i] = entrys[i].strip()
    if len(entrys[i]) != 0:
        newEntrys.append(entrys[i])
entrys = newEntrys[:]

blocks = []

for e in entrys:
    overwriteType = e.find("//") 
    type = ""
    name = ""
    if overwriteType != -1:
        type = e[overwriteType+2:]
    else:
        temp = e.rfind(" ")
        type = e[:temp]
    temp = e.find(";")
    name = e[e[:temp].rfind(" "):temp]

    blocks.append([type.strip(), name.strip()])

packStr = f"""int pack_{structName}(unsigned char* out, {structName}* {structNameLower}){'{'}
unsigned char* iter = out;

"""
unpackStr = f"""int unpack_{structName}({structName}* {structNameLower}, unsigned char* in){'{'}
unsigned char* iter = in;

"""
lengthStr = f"""int length_{structName}({structName}* {structNameLower}){'{'}
int length = 0;

"""
freeStr = f"""void free_{structName}({structName}* {structNameLower}){'{'}
"""
for b in blocks:
    advanceBlock = f"iter += {lengthTable[b[0]]};"
    temp = f"{packTable[b[0]]}" + advanceBlock + "\n\n"
    temp = temp.replace("[length]",f"{lengthTable[b[0]]}").replace("[value]",f"{structNameLower}->{b[1]}")
    packStr += temp

    temp = f"{unpackTable[b[0]]}" + advanceBlock + "\n\n"
    temp = temp.replace("[length]",f"{lengthTable[b[0]]}").replace("[value]",f"{structNameLower}->{b[1]}")
    unpackStr += temp

    temp = f"length += {lengthTable[b[0]]};\n"
    temp = temp.replace("[length]",f"{lengthTable[b[0]]}").replace("[value]",f"{structNameLower}->{b[1]}")
    lengthStr += temp;

    if b[0] == 'unsigned char*':
        temp = f"free({structNameLower}->{b[1]});\n"
        freeStr += temp;

packStr += "return 0;\n}"
unpackStr += "return 0;\n}"
lengthStr += "return length;\n}"
freeStr += "}"

newFunctions = f"{packStr}\n{unpackStr}\n{lengthStr}\n{freeStr}\n\n"

# print(packStr)
# print(unpackStr)
# print(lengthStr)
# print(freeStr)


cFileName = fileName[0:fileName.rfind(".")].strip()+'.c'
writeFile = ""
includeHeader = f'#include "{fileName}"\n'
addInclude = False
if os.path.isfile(cFileName):
    filePtr = open(cFileName,"r")
    file = filePtr.read()
    filePtr.close()

    addInclude  = True if file.find(includeHeader) == -1 else False

    startGenerated = file.find(startBuildScriptTag)
    endGenerated = file.find(endBuildScriptTag) + len(endBuildScriptTag)

    if startGenerated == -1 or endGenerated == -1:
        writeFile = file[::] + startBuildScriptTag + '\n' + (includeHeader if addInclude else "") + newFunctions + endBuildScriptTag
    else:
        writeFile = file[:startGenerated] + file[endGenerated:] + startBuildScriptTag + '\n' + (includeHeader if addInclude else "") + newFunctions + endBuildScriptTag
else:
    writeFile = startBuildScriptTag + includeHeader + newFunctions + endBuildScriptTag

filePtr = open(cFileName, "w")
filePtr.write(writeFile)
filePtr.close()

# print("build and wrote the new c file!")